name: Trigger auto deployment for npact-api-dc-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/npact-api-dc-dev-AutoDeployTrigger-012da953-ad5f-4487-bbc6-0ad4ea69038e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NPACTAPIDCDEV_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca5caa846c4cacr.azurecr.io
          registryUsername: ${{ secrets.NPACTAPIDCDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NPACTAPIDCDEV_REGISTRY_PASSWORD }}
          containerAppName: npact-api-dc-dev
          resourceGroup: rg-dev-dc-central-001
          imageToBuild: ca5caa846c4cacr.azurecr.io/npact-api-dc-dev:${{ github.sha }}
          

     

